name: Publish iOS App

on:
  push:
    # WorkfloaからのPushではTriggerされないため注意が必要
    tags:
      - 'bundle[0-9]+.[0-9]+.[0-9]+'

  workflow_run:
    workflows:
      - Assign Bundle ID tags (main)
      - Assign Bundle ID tags (Pull Request)
    types:
      - completed

env:
  CSPROJ_PATH: ./AirTote/AirTote.csproj
  IPA_PATH: ./AirTote/bin/Publish/net6.0-ios/ios-arm64/publish/AirTote.ipa

jobs:
  build-ios:
    if: |
      github.event_name == 'push'
      || github.event.workflow_run.conclusion == 'success'

    runs-on: [self-hosted, macOS]
    steps:
    - uses: actions/checkout@v2

    - name: fetch related tag
      run: git fetch --no-recurse-submodules --depth=1 origin +${{ github.sha }}:refs/remotes/origin/${{ github.ref_name }}

    - name: get version number
      run: |
        git tag --points-at ${{ github.sha }} | tr -d bundle > VERSION_NUMBER

    - name: print version number
      run: echo "VersionNumber (Bundle Version) ..." `cat VERSION_NUMBER`

    - name: Install dependencies
      run: dotnet restore ${{ env.CSPROJ_PATH }}

    - name: Build
      run: >
        dotnet publish ${{ env.CSPROJ_PATH }}
        -f:net6.0-ios
        -r ios-arm64
        -c Publish
        /p:ApplicationVersion=`cat VERSION_NUMBER`
        /p:ApplicationDisplayVersion=`cat VERSION_NUMBER | awk -F '.' '{print $1 "." $2}'`
    
    - name: validate
      run: >
        xcrun altool
        --validate-app
        --type ios
        -f ${{ env.IPA_PATH }}
        --apiKey ${{ secrets.APPSTORECONNECT_API_KEY }}
        --apiIssuer ${{ secrets.APPSTORECONNECT_ISSUER_ID }}

    - name: upload
      run: >
        xcrun altool
        --upload-app
        --type ios
        -f ${{ env.IPA_PATH }}
        --apiKey ${{ secrets.APPSTORECONNECT_API_KEY }}
        --apiIssuer ${{ secrets.APPSTORECONNECT_ISSUER_ID }}

    - name: Upload IPA
      uses: actions/upload-artifact@v3.0.0
      with:
        name: ipa
        path: ${{ env.IPA_PATH }}
        retention-days: 3
